module.exports = {
  getZones: require('./tiendas/getZones'),
  getTiendasByZone: require('./tiendas/getTiendasByZone'),
  getFuenteTiendaByName: require('./tiendas/getFuenteTiendaByName'),
  getToken: require('./token/getToken'),
  formatRut: require('./formats/rutFormater'),
  siebelFormatDocument: require('./formats/siebelFormatDocument'),
  getClientInfo: require('./clientInfo/getClientInfo'),
  calcularSolicitudListadoObtener: require('./listadoSolicitud/calcularSolicitudListadoObtener'),
  calcularSolicitudListadoObtenerPorOC: require('./listadoSolicitud/calcularSolicitudListadoObtenerPorOC'),
  calcularSolicitudListadoObtenerReturnArray: require('./listadoSolicitud/calcularSolicitudListadoObtenerReturnArray'),
  solicitudListadoObtener: require('./listadoSolicitud/solicitudListadoObtener'),
  solicitudDetalleObtener: require('./listadoSolicitud/solicitudDetalleObtener'),
  formatInfo: require('./formats/formatInfo'),
  getStock: require('./stock/getStock'),
  createSR: require('./ss/createSR'),
  createFCR: require('./ss/createFCR'),
  subOrders: require('./subOrdenes/subOrders'),
  subOrdersProductos: require('./subOrdenes/subOrdersProductos'),
  simpleFormatInfo: require('./formats/simpleFormatInfo'),
  simpleCreatesSS: require('./ss/simpleCreatesSS'),
  validarDuplicidadSS: require('./ss/validarDuplicidadSS'),
  clienteSubOrdenObtener: require('./subOrdenes/clienteSubOrdenObtener'),
  CrearNotaCredito: require('./actividades/crearNotaCredito'),
  datosClientesPorOc: require('./subOrdenes/datosClientesPorOc'),
  clienteSubOrdenObtenerLineas: require('./subOrdenes/clienteSubOrdenObtenerLineas')
}
