// Redirección a carpetas con diálogos

module.exports = () => {
    require('./actualizacion_datos_cmr')
    require('./anulacion_orden_compra')
    require('./anulacion_pendiente')
    require('./armado_producto')
    require('./beneficios_club_bebe')
    require('./bloqueo_tarjeta_cmr')
    require('./chit_chat_amistad')
    require('./chit_chat_ayuda')
    require('./chit_chat_casate_conmigo')
    require('./chit_chat_chistes')
    require('./chit_chat_clima')
    require('./chit_chat_como_te_llamas')
    require('./chit_chat_de_donde_eres')
    require('./chit_chat_despedida')
    require('./chit_chat_donde_trabajas')
    require('./chit_chat_eres_real')
    require('./chit_chat_estado')
    require('./chit_chat_estado_civil')
    require('./chit_chat_estado_familiar_agente')
    require('./chit_chat_fecha_actual')
    require('./chit_chat_fecha_cumpleanos')
    require('./chit_chat_gracias')
    require('./chit_chat_gusto_futbol')
    require('./chit_chat_hora_actual')
    require('./chit_chat_horario_trabajo_agente')
    //chit_chat_insulto se utilizara en el codigo
    require('./chit_chat_que_edad_tienes')
    require('./chit_chat_que_haces')
    require('./chit_chat_salario_de_agente')
    require('./chit_chat_saludo')
    require('./chit_chat_te_gustaria_ser_humano')
    require('./chit_chat_tienes_hambre')
    require('./chit_chat_usuario_aburrido')
    require('./chit_chat_usuario_cansado')
    require('./chit_chat_usuario_contento')
    require('./chit_chat_usuario_enojado')
    // chit_chat_usuario_riendo se utiliza en codigo
    require('./chit_chat_usuario_suicida')
    require('./chit_chat_usuario_tiene_sueno')
    require('./chit_chat_usuario_triste')
    require('./callback_no_realizado')
    require('./cambio_boleta_factura')
    //require('./cambio_direccion_despacho')
    require('./cambio_fecha_despacho')
    require('./cambio_producto')
    require('./clave_cmr')
    require('./como_eliminar_producto')
    require('./como_obtener_sku')
    require('./comparar_productos')
    require('./compra_garantia_extendida')
    require('./compra_y_retira_diferentes_tiendas')
    require('./consulta_extranjero')
    require('./consulta_extranjero_despacho')
    require('./consulta_reclamo')
    require('./consulta_stock')
    //require('./consultas_y_dudas') ya no se ocupara debido a cambio de menu
    require('./contacto_garantia_extendida')
    require('./contacto_servicio_al_cliente')
    require('./contacto_servicio_tecnico')
    //*************************** */
    //require('./copia_boleta')
    //*************************** */
    require('./correo_confirmacion_no_recibido')
    require('./costo_despacho')
    require('./definicion_club_deco')
    require('./descripcion_garantia_extendida')
    //require('./devolucion_producto')
    require('./estado_servicio_tecnico')
    require('./explicacion_procedimiento_compra')
    require('./generico_clave')
    require('./generico_otros_negocios')
    require('./gerente_tienda')
    require('./getsurvey')
    require('./horario_despacho')
    require('./horario_tienda')
    //require('./incumplimiento_reclamo')
    require('./informacion_banco_falabella')
    require('./informacion_club_bebe')
    require('./informacion_club_deco')
    require('./informacion_club_novios')
    require('./informacion_gift_card')
    require('./informacion_orden_compra') //(es estado_webtracking)
    require('./informacion_postventa')
    require('./informacion_retiro_tienda')
    require('./informacion_seguros_falabella')
    require('./informacion_tarjeta_cmr')
    require('./informacion_ventas')
    require('./informacion_viajes_falabella')
    require('./ingreso_reclamo')
    require('./jefe_tienda')
    require('./lugares_para_despacho')
    require('./modificacion_datos_orden_compra')
    require('./no_me_sirve')
    require('./opciones_medio_pago')
    require('./pagina_web_cmr')
    require('./pagina_web_falabella')
    require('./periodo_vigencia_garantia')
    require('./plazo_retiro_tienda')
    require('./plazos_club_deco')
    require('./politicas_postventa')
    require('./preguntas_frecuentes_cupon_descuento')
    require('./preguntas_frecuentes_empresa_venta')
    require('./preguntas_frecuentes_homy')
    require('./preguntas_frecuentes_sodimac')
    require('./preguntas_frecuentes_tottus')
    require('./problemas_compra')
    require('./problemas_productos') //nuevo
    require('./producto_descompuesto')
    require('./productos_club_bebe')
    require('./productos_ordenes_compra')
    require('./puntos_club_bebe')
    require('./puntos_club_deco')
    require('./puntos_cmr')
    require('./puntos_compras_club_deco')
    require('./queja_mal_servicio')
    require('./quiero_buscar_producto')
    require('./quiero_comprar_producto')
    require('./servicio_instalacion')
    require('./servicio_reciclaje')
    require('./reclamo_tipificaciones')
    require('./reclamos_despacho') //nuevo
    require('./problema_pagina_web') //nuevo
    require('./registro_web_falabella')
    require('./requisitos_retiro_tienda')
    require('./retiro_fuera_plazo_tienda')
    require('./retiro_tienda_no_puedo_retirar')
    require('./sernac_reclamo')
    require('./sin_respuesta_garantia_extendida')
    require('./solicitud_callback')
    require('./tengo_una_pregunta')
    require('./terminar_contrato_cmr')
    require('./tienda_inexistente')
    require('./tiendas_club_bebe')
    require('./ubicacion_tienda')
    require('./venta_telefonica')
    //catalogo navidad
    require('./catalogo_navidad')
    //#########
    require('./none')
    require('./salida')
    //documentos tributarios
    require('./documentos_tributarios/boleta')
    require('./documentos_tributarios/datos_documentos_tributarios')
    require('./documentos_tributarios/nota_credito')
    require('./solicitud_callback_general')
    //Beneficios dia de la madre
    require('./dia_de_la_madre')
    //################################BO################################
    require('./quiebre_backoffice')
    require('./quiebre_backoffice/callback_quiebre')
    require('./quiebre_backoffice/giftcard_quiebre')
    require('./quiebre_backoffice/login_quiebre_backoffice')
    require('./quiebre_backoffice/quiebre_atendido')
    require('./inscripcion_club_bebe')


}